<a href="https://colab.research.google.com/github/prexia/THC/blob/desarollo/Clase_24_10_23.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8]) #Python empieza en 0 y no da el ultimo valor que marcas

print(arr[2:6]) #Va a imprimir del valor 3 hasta el 6

[3 4 5 6]


In [4]:
arr=np.array([1,2,3,4,5,6,7,8])

print(arr[1:]) #Si el intervalo no termina en nada se va hasta el final

[2 3 4 5 6 7 8]


In [6]:
arr=np.array([1,2,3,4,5,6,7,8])

print(arr[-3:-1]) #El ultimo valor es igual al -1 y asi se va hacia los negativos hasta llegar al primer termino
print(arr[-1])

[6 7]
8


In [7]:
arr=np.array([1,2,3,4,5,6,7,8])

print(arr[1:5:2])#El tercer elemento (2) en este caso es el paso, el cual nos dice que van de dos en dos, imprime del valor 1 al 5 de dos en dos

[2 4]


In [11]:
arr=np.array([1,2,3,4,5,6,7,8])

print(arr[::2])#Si no pones nada en los primeros dos terminos, y el paso es de dos en dos imprime todo de dos en dos

[1 3 5 7]


In [16]:
arr=np.array([1,2,3,4,5,6,7,8])

print(arr[::3])#de 3 en 3
#::1 imprime todod
#0: imprime todo
#:0 no imprime nada

[1 4 7]


In [20]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,1:4]) #El primer termino determina el renglon y como empienza en 0 agarra el segundo  y el segundo la columna

[7 8 9]


In [21]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,:]) #Imprime todo el renglon

[ 6  7  8  9 10]


In [26]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,2]) #Como el sengundo termino determina las columnas, va a agarra elementos de la columna 3 en este caso el 3=0 y el 8=1 ya que el 2 no se toma en cuenta

[3 8]


In [27]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,3])

[4 9]


In [29]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,1:4]) #Agaramos del renglon 0 y 1 y agarramos elemento de las columnas 1,2,3 del renglon 0 y del 1

[[2 3 4]
 [7 8 9]]


In [34]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:1,2:5]) #Solo del primer renglon o renglon 0 y a las columnas,2,3,4

[[3 4 5]]


In [35]:
arr= np.array([1,2,3,4,5,4,4])
x = np.where(arr==4) #Los indices de los elementos que sean 4
print(x)

(array([3, 5, 6]),)


In [36]:
arr= np.array([1,2,3,4,5,4,4])
x = np.where(arr%2==0) #los indices de los elemnetos divisibles entre dos
print(x)

(array([1, 3, 5, 6]),)


In [38]:
arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr] #Para que te entregue numeros, mascara buleana

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [39]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]


In [50]:
x=np.array([1,2,3])
y=np.array([4,5,6])
suma=x+y
print(f"La suma es {suma}")
multiplicación=x*y
print(f"La multiplicacion es {multiplicación}")
resta=y-x
print(f"La resta es {resta}")
division=x/y
print(f"La division es { division}")
print(f"El Numero pi={np.pi}")


La suma es [5 7 9]
La multiplicacion es [ 4 10 18]
La resta es [3 3 3]
La division es [0.25 0.4  0.5 ]
El Numero pi=3.141592653589793


In [52]:
angulos=np.array([0,np.pi/2,np.pi])
seno=np.sin(angulos)
print(f"Los senos{seno}")
print(f"De los angulos{angulos}")


Los senos[0.0000000e+00 1.0000000e+00 1.2246468e-16]
De los angulos[0.         1.57079633 3.14159265]


In [54]:
angulos=np.array([0,np.pi/2,np.pi])
coseno=np.cos(angulos)
print(f"Los cosenos {coseno}")
print(f"De los angulos{angulos}")

Los cosenos [ 1.000000e+00  6.123234e-17 -1.000000e+00]
De los angulos[0.         1.57079633 3.14159265]


In [57]:
x=np.array(list(range(1,9)))
print(x)

[1 2 3 4 5 6 7 8]


In [58]:
matriz=x.reshape(2,4)
matriz

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [59]:
matriz=x.reshape(4,2)
matriz

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [63]:
x=np.linspace(0,1,4)#Tercer elemento el paso en el inervalo de 0,1
x

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [64]:
np.random.uniform(0,1,6)

array([0.00308475, 0.87270921, 0.94123268, 0.51000477, 0.16763005,
       0.4490623 ])

In [66]:
np.random.randint(0,10,size=3)

array([6, 6, 7])

Ejercicio numero aleatorio

In [109]:
arr=np.array(list(range(1,11)))
x=float(input("Ingrese un numero del 1 al 10 "))
np.random.randint(0,11,1)

Ingrese un numero del 1 al 10 4


array([4])