<a href="https://colab.research.google.com/github/prexia/THC/blob/desarollo/Clase_19_10_2023.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
arr = np.array([1,2,3,4,5]) #Lista adentro del parentesis

print(arr)
print(type(arr)) #Te imprime un arreglo


[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
arr1= np.array((1,2,3,4,5)) #Tupla dentro del parentesis

print(arr)
print(type(arr))#Te imprime un arreglo

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
#Arreglo 0 Dimensional 0-D (Punto)
arr= np.array(42)

print(arr)

42


In [6]:
#Arreglo 1-D (Linea)
arr = np.array([1,2,3,4,5])

print(arr)

[1 2 3 4 5]


In [5]:
#Arreglo Bidimensional 2-D (Cuadrado)
arr = np.array([[1,2,3],[4,5,6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [12]:
#Arreglos Tridimensionales 3-D (Cubo)
arr = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [17]:
a = np.array(42)
b = np.array([1,2,3,4,5])
c= np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
#Primer Valor la cantidad de elementos
#En los parentesis la cantidad de renglones, columnas
print(a.ndim,a.shape)
print(b.ndim,b.shape)
print(c.ndim,c.shape)
print(d.ndim,d.shape)

0 ()
1 (5,)
2 (2, 3)
3 (2, 2, 3)


In [ ]:
arr = np.array([])

In [19]:
arr = np.array([1,2,3,4])
print(arr[0])
print(arr[3])

1
4


In [22]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("El segundo elemento de la fila:",arr[0,1]) #Pirmer valor el numero de la matriz, el segundo el lugar del valor
print(arr[1,4])
print(arr[0,3])

El segundo elemento de la fila: 2
10
4


In [26]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
                   #0           #1          #0           #1
print(arr[1,1,1])
print(arr[0,1,0])

11
4


In [35]:
A=[[1,2,3],[6,7,8],[9,10,11]]
for i in range (len(A)):
  for j in range (len(A)):
    print([i]+[j])



[0, 0]
[0, 1]
[0, 2]
[1, 0]
[1, 1]
[1, 2]
[2, 0]
[2, 1]
[2, 2]


In [41]:
arr = np.array=([[1,2,3],[4,5,6],[7,8,9]])
for i in arr:
  for j in arr:
    print([i]+[j])

[[1, 2, 3], [1, 2, 3]]
[[1, 2, 3], [4, 5, 6]]
[[1, 2, 3], [7, 8, 9]]
[[4, 5, 6], [1, 2, 3]]
[[4, 5, 6], [4, 5, 6]]
[[4, 5, 6], [7, 8, 9]]
[[7, 8, 9], [1, 2, 3]]
[[7, 8, 9], [4, 5, 6]]
[[7, 8, 9], [7, 8, 9]]


In [50]:
def suma_de_matrices(A,B,H):
  if len(A)==len(B)==len(H):
      n=len(A)
      C=n*[1.1]
      D=0
      for i in range (n):
        C[i]=A[i]+B[i]+H[i]
        D=C[i]+D
      print(D)
  else:
    print(NO)
suma_de_matrices(A=[1,1,1],B=[1,1,1],H=[1,1,1])

9


In [10]:
import numpy as np
arr = np.array([[1,1,1],[1,1,1],[1,1,1]])
Suma=0
for i in range(len(arr)):
  for j in range(len(arr[i])):
    Suma=Suma+arr[i,j]
print(Suma)

9


In [4]:
import numpy as np
arr = np.array([[1,1,1],[1,1,1],[1,1,1]])
for i in range(len(arr)):
  for j in range(len(arr)):
    print(i*j)

0
0
0
0
1
2
0
2
4


In [9]:
#EJERCICIO BIEN HECHO
A=[[1,1,1],[1,1,1],[1,1,1]]
suma=0
for i in range(len(A)):
    for j in range(len(A)):
      suma=suma+A[i][j]
print(suma)

9


In [20]:
def ProdPunto(a,b):
  #Para Listas
  for i in range(len(a)):
    PP=0.0
    PP=a[i]*b[i]
  return PP

In [22]:
arr2=np.array([[1,1,1],[1,1,1],[1,1,1]])
arr3=np.array([[1,1,1],[1,1,1],[1,1,1]])
arr2[0]
Pp_por_rengl=np.array([0,0,0])
Pp_por_col=np.array([0,0,0])
for i in range(len(arr2)):
  Pp_por_rengl[i]=ProdPunto(arr2[i],arr3[i])
Pp_por_rengl

array([1, 1, 1])

In [29]:
def AC(a,col):
  nuevo=[]
  for i in range(len(a)):
    nuevo.append(a[i,col])

    return np.array(nuevo)
    col1=AC(arr2,0)
    col1



In [28]:
for i in range(len(arr2)):
  Pp_por_col[i]=ProdPunto(AC(arr2,1),AC(arr3,i))
Pp_por_col

array([1, 1, 1])